### PR TITLE
Start/end frames, BT.2020 HEVC output, adjusted label/flash location, all Python 3

### PR DESCRIPTION
**Pull request by nicholas-fr**
Added the following functionality:
- Added optional start (dark green) and/or end (dark red) frames to signal the start/end of the test stream using the `--start-end-indicators` argument. Would it be useful to use a test pattern for the first frame instead or is a single color best for test automation reasons?
- Added support for BT.2020 HDR output. If the source content is BT.2020, the script encodes the output using HEVC. (Note: ffmpeg ProRes output colorspace, primaries and transfer function signalling does not seem to be working as expected.)

Change:
- Location of label and AV sync flash adjusted to provide enough space for a JS app to also display a timecode (top-centre) and QR code (right side of the screen).
new

Changes to address issues from Zack's review:
- Added requirements.txt and updated the README with some more details (once we agree on the final version we can clean up/merge the older parts).
- All scripts now require Python 3 instead of a mix of Python 2 and 3. Used 2to3 to translate the test sequence generator scripts to Python 3 and resolved a new related issue.
- Now uses pathlib to avoid using OS-specific directory paths.

Remaining issues to look into:
- Avoid generating QR codes, flashes and beeps into files and instead directly synthesize them in memory.
- Adapt annotations when source content is HDR (to avoid overly bright graphics).
- From Eurofins comments in issue #1 : "To make automated capture easy it may be necessary to silence spoken audio either side of the beeps". - This isn't done at present. If this is still a concern, perhaps the weighting of the original source audio vs the beeps can be adjusted to avoid any detection issues.
- From Eurofins comments in issue #1 : "We would suggest having an audio tone at the start (for audio start up delay) and end, and at a consistent jump to point (e.g. 20s) to enable automated checking." - Can add a tone to accompany the start/end frames. Considering the irregular AV sync pattern repeats after a configurable duration, do we need to additionally define a specific jump point?
- Comment in issue #1 : "With the audio need to make sure that every audio sample has a defined start and end tone (apply a different frequency than the beep - could also be a short jingle (identifying) and it is longer - like 1 seconds)." - The configurable irregular AV sync pattern should already address this, but to be confirmed.

### CODE REVIEW

**Comment by nicholas-fr** [comment]
Resolves #10 , resolves #9.

**Comment by nicholas-fr** [comment]
Updated `mezzanine.py`:
- Inverted QR codes (now white on black), to minimize amount of peak white graphics shown.
- Added 1kHz beep to accompany start/end indicator frames.
- Made configuration of start/end frame colour and duration easier.
- Fixed outdated parameters for start only and end only indicator frame options.

**Comment by nicholas-fr** [comment]
Updated `mezzanine.py`:
- Fix for fractional frame rate handling (confirmation from a reviewer would be welcome).
- Increased precision of timecode written to QR codes to match with timecode displayed by ffmpeg, as there was a mismatch with longer content durations.

**Comment by haudiobe** [comment]
Please add the non-tracked issues to the issue tracker

**Pull request merged**
